meta:
  engine: 4.2.1
units:
  kx: cx
  ky: cy
  px: kx + 4
  py: ky + 4
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        shift: [100, -100]
        rotate: 20
      columns:
        pinky:
          key.column_net: P0
        ring:
          key.splay: -5.5
          key.origin: [-12, -19]
          key.column_net: P1
          key.stagger: 8
        middle:
          key.splay: -5.5
          key.stagger: 7
          key.spread: 1.1kx
          key.column_net: P2
        index:
          key.column_net: P3
          key.stagger: -8
        inner:
          key.column_net: P4
          key.stagger: -2
      rows:
        bottom:
          row_net: P5

        home:
          row_net: P6
        top:
          row_net: P7
    thumbfan:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_bottom
        shift: [1, -20]
      columns:
        near:
          key.column_net: P2
        home:
          key.column_net: P3
          key.spread: 20
          key.splay: -28
          key.origin: [-11.75, -9]
        far:
          key.column_net: P4
          key.spread: 20
          key.splay: -28
          key.origin: [-9.5, -9]
      rows:
        thumb:
          row_net: P8

    pinky-extra:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_pinky_bottom
        shift: [-kx, 5]
      columns:
        pinky2:
          key.column_net: P8
      rows:
        extra1:
          row_net: P0
        extra2:
          row_net: P1
  mirror:
    ref: thumbfan_far_thumb
    distance: 3kx

outlines:
  board1:
    - what: rectangle
      where: true
      size: [px, py]
    - what: rectangle
      where: matrix_pinky_top
      adjust.shift: [1px, .1py]
      size: [3px, .8py]

    - what: rectangle
      where: matrix_ring_top
      adjust.shift: [.5px, .1py]
      size: [0.2px, .8py]

    - what: rectangle
      where: thumbfan_near_thumb
      adjust.shift: [-.1px, 0py]
      size: [.89px, 1py]
    - what: rectangle
      where: matrix_index_top
      adjust.shift: [0px, 0.099py]
      size: [px, 1py]
    - what: rectangle
      where: matrix_inner_top
      adjust.shift: [.9px, -1.3py]
      size: [.9px, 3.6py]

    - what: rectangle
      where: mirror_matrix_pinky_top
      adjust.shift: [1px, .1py]
      size: [3px, .8py]

    - what: rectangle
      where: mirror_matrix_ring_top
      adjust.shift: [.5px, .1py]
      size: [0.2px, .8py]
    - what: rectangle
      where: mirror_thumbfan_near_thumb
      adjust.shift: [-.1px, 0py]
      size: [.89px, 1py]
    - what: rectangle
      where: mirror_matrix_index_top
      adjust.shift: [0px, 0.099py]
      size: [px, 1py]
    - what: rectangle
      where: mirror_matrix_inner_top
      adjust.shift: [.9px, -1.3py]
      size: [.9px, 3.6py]

  popa:
    - what: polygon
      operation: stack
      points:
        - ref: thumbfan_near_thumb
          shift: [0px, .5py]
        - ref: thumbfan_home_thumb
          shift: [-.5px, .5py]
        - ref: thumbfan_home_thumb
          shift: [.5px, .5py]
        - ref: thumbfan_far_thumb
          shift: [-.5px, .5py]
        - ref: thumbfan_far_thumb
          shift: [.5px, .5py]
        - ref: thumbfan_far_thumb
          shift: [.5px, -.5py]
        - ref: thumbfan_home_thumb
          shift: [.5px, -.5py]
        - ref: thumbfan_near_thumb
          shift: [0.3px, -.5py]
    - what: polygon
      operation: stack
      points:
        - ref: mirror_thumbfan_near_thumb
          shift: [0px, .5py]
        - ref: mirror_thumbfan_home_thumb
          shift: [-.5px, .5py]
        - ref: mirror_thumbfan_home_thumb
          shift: [.5px, .5py]
        - ref: mirror_thumbfan_far_thumb
          shift: [-.5px, .5py]
        - ref: mirror_thumbfan_far_thumb
          shift: [.5px, .5py]
        - ref: mirror_thumbfan_far_thumb
          shift: [.5px, -.5py]
        - ref: mirror_thumbfan_home_thumb
          shift: [.5px, -.5py]
        - ref: mirror_thumbfan_near_thumb
          shift: [0.3px, -.5py]

  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board:
    - name: board1
    - operation: add
      name: popa
      #    - operation: subtract
      #      name: keys
      fillet: 2

pcbs:
  right:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: switch_choc_v1_v2
        where: true
        params:
          include_keycap: true
          side: B
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [3, -5]
      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          side: B
          from: GND
          to: RST
          include_courtyard: true
        where:
          ref: mirror_matrix_inner_top
          shift: [-.9px, 0.5py]
          rotate: 0
      power:
        what: ceoloide/power_switch_smd_side
        params:
          side: B
        where:
          ref: mirror_matrix_inner_top
          shift: [.2px, .5py]
          rotate: 90
      slider:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
          ref: mirror_thumbfan_near_thumb
          shift: [1px, 1py]
          rotate: 90
      batt-con:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: mirror_matrix_inner_top
          shift: [1px, -.2py]
          rotate: -90
        params:
          side: B
